### ISSUE TITLE
A partir de la versión 2.1.0 no he podido firmar ningún PDF

### ISSUE THREAD

**Issue by eusonlito** [universitatjaumei/cryptoapplet#3]
El error siempre es:

```
ERROR thread-sig-0 es.uji.security.ui.applet.SignatureThread [20:06:25,509] - <html><font color='red'>No se ha podido calcular la firma</font></html>
java.lang.NullPointerException
    at com.lowagie.text.pdf.AcroFields.removeField(AcroFields.java:1472)
    at com.lowagie.text.pdf.AcroFields.removeField(AcroFields.java:1504)
    at com.lowagie.text.pdf.PdfSignatureAppearance.preClose(PdfSignatureAppearance.java:891)
    at es.uji.security.crypto.pdf.PDFSignatureFactory.sign(PDFSignatureFactory.java:131)
    at es.uji.security.crypto.pdf.PDFSignatureFactory.addVisibleSignatureAndSign(PDFSignatureFactory.java:371)
    at es.uji.security.crypto.pdf.PDFSignatureFactory.formatSignature(PDFSignatureFactory.java:340)
    at es.uji.security.ui.applet.SignatureThread.run(SignatureThread.java:465)
DEBUG thread-sig-0 es.uji.security.ui.applet.AppHandler [20:06:25,510] - Call JavaScript method: onSignError
es.uji.security.ui.applet.SignatureAppletException
    at es.uji.security.ui.applet.SignatureThread.run(SignatureThread.java:473)
```

Con la versión 2.1.0 puedo firmar sin problema cualquier pdf.

Los ficheros incluidos son:

```
uji-config-2.1.8-SNAPSHOT.jar
uji-format-facturae-2.1.8-SNAPSHOT.jar
uji-utils-2.1.8-SNAPSHOT.jar
MicrosoftCryptoApi_0_3.dll
xmlsec-backport-jdk6-1.6.0_15.jar
uji-crypto-xmldsign-2.1.8-SNAPSHOT.jar
uji-format-odf-2.1.8-SNAPSHOT.jar
jakarta-log4j-1.2.6.jar
uji-crypto-mityc-2.1.8-SNAPSHOT.jar
uji-crypto-raw-2.1.8-SNAPSHOT.jar
uji-format-pdf-2.1.8-SNAPSHOT.jar
myxmlsec.jar
bcmail-jdk15-143.jar
xalan-2.7.0.jar
uji-crypto-jxades-2.1.8-SNAPSHOT.jar
ujiCrypto.conf
uji-keystore-2.1.8-SNAPSHOT.jar
bctsp-jdk15-143.jar
commons-logging.jar
bcprov-jdk15-143.jar
uji-crypto-core-2.1.8-SNAPSHOT.jar
xmlsec.jar
uji-crypto-cms-2.1.8-SNAPSHOT.jar
uji-crypto-openxades-2.1.8-SNAPSHOT.jar
uji-ui-applet-2.1.8-SNAPSHOT.jar
itext-1.4.8.jar
```

Los ficheros incluidos en la versión 2.1.0:

```
uji-keystore-2.1.0-signed.jar
uji-crypto-core-2.1.0-signed.jar
uji-format-facturae-2.1.0-signed.jar
uji-utils-2.1.0-signed.jar
uji-crypto-openxades-2.1.0-signed.jar
MicrosoftCryptoApi_0_3.dll
uji-format-odf-2.1.0-signed.jar
xmlsec-backport-jdk6-1.6.0_15.jar
jakarta-log4j-1.2.6.jar
uji-crypto-mityc-2.1.0-signed.jar
uji-crypto-jxades-2.1.0-signed.jar
myxmlsec.jar
bcmail-jdk15-143.jar
xalan-2.7.0.jar
uji-ui-applet-2.1.0-signed.jar
uji-config-2.1.0-signed.jar
ujiCrypto.conf
bctsp-jdk15-143.jar
commons-logging.jar
uji-format-pdf-2.1.0-signed.jar
bcprov-jdk15-143.jar
uji-crypto-xmldsign-2.1.0-signed.jar
xmlsec.jar
uji-crypto-raw-2.1.0-signed.jar
uji-crypto-cms-2.1.0-signed.jar
itext-1.4.8.jar
```

**Comment by borillo** [comment]
Please, review the last versión 2.1.8 for a lot of improvements in PDF generation.
